# ----
# Site

title: XT DOC
description: XT Interface documentation.
url: https://doc.xt.com
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Access Description
    position_number: 1
  quotes:
    title: Market data
    position_number: 2
  order:
    title: Order
    position_number: 3
  entrust:
    title: Entrust
    position_number: 4
  user:
    title: User
    position_number: 5
  websocket:
    title: WEBSOCKET
    position_number: 6
  documentation_cn:
    title: 接入说明
    position_number: 7
  quotes_cn:
    title: 行情数据
    position_number: 8
  order_cn:
    title: 限价委托和市价委托
    position_number: 9
  entrust_cn:
    title: 计划委托与止盈止损
    position_number: 10
  user_cn:
    title: 用户相关
    position_number: 11
  websocket_cn:
    title: WEBSOCKET
    position_number: 12
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CNAME
  - favicon.ico
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - robots.txt


defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "quotes"
    values:
      _hide_content: true
  -
    scope:
      type: "order"
    values:
      _hide_content: true
  -
    scope:
      type: "entrust"
    values:
      _hide_content: true
  -
    scope:
      type: "user"
    values:
      _hide_content: true
  -
    scope:
      type: "websocket"
    values:
      _hide_content: true
  -
    scope:
      type: "documentation_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "quotes_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "order_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "entrust_cn"
    values:
      _hide_content: true
  -
    scope:
      type: "user_cn"
    values:
      _hide_content: true
  -
  -
    scope:
      type: "websocket_cn"
    values:
      _hide_content: true
# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css